#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

if ! command -v "git-lfs" &> /dev/null
then
    echo "COMMAND "git lfs" could not be found"
    echo "Please install git-lfs support, see: https://git-lfs.github.com/"
    exit
fi

git lfs pull

echo "Symlink configuration"
cp .build/vendor/typo3/cms-install/Resources/Private/FolderStructureTemplateFiles/root-htaccess .build/public/.htaccess
mkdir -p .build/config/sites/main
ln -snf ../../../../.project/typo3/config.yaml .build/config/sites/main/config.yaml
mkdir -p .build/config/system
ln -snf ../../../.project/typo3/settings.php .build/config/system/settings.php
ln -snf ../../../.project/typo3/additional.php .build/config/system/additional.php

echo "Importing database"
ddev import-db --file=.project/data/db.sql.gz

echo "Run 'composer install'"
ddev composer install

echo "Extracting fileadmin"
tar xf .project/data/fileadmin.tar.gz -C .build/public/

echo "Copy .htaccess"
cp .build/vendor/typo3/cms-install/Resources/Private/FolderStructureTemplateFiles/root-htaccess .build/public/.htaccess

echo "Update Languages (needed for behaviour tests)"
ddev typo3 language:update

ddev describe

echo "Thanks for supporting 'EXT:powermail"
